<a href="https://colab.research.google.com/github/deepen-404/pytorch-machine-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch;
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.4.1+cu121


In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get Scalar as a python int
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
# no of pair of sq bracets = no of dimensions

vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])
print(MATRIX.ndim)
print(MATRIX.shape)
MATRIX

2
torch.Size([2, 2])


tensor([[1, 2],
        [3, 4]])

In [ ]:
print(MATRIX[0])
print(MATRIX[1])

tensor([1, 2])
tensor([3, 4])


In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 4, 3])


In [ ]:
TENSOR = torch.tensor([[[1, 2, 3, 4],
                        [1, 2, 3, 4],
                        [4, 5, 6, 4],
                        [7, 8, 9, 4]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3, 4],
         [1, 2, 3, 4],
         [4, 5, 6, 4],
         [7, 8, 9, 4]]])
3
torch.Size([1, 4, 4])


In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[1, 2, 3],
                        [1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([2, 4, 3])


# Random Tensors
Why random tensors??

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers
and adjust those random numbers to better represent the data

`Start with random nubmer -> look at data -> update random numbers -> look at data -> update random numbers `

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 3, 4)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[[0.0503, 0.9106, 0.7554, 0.0068],
         [0.4413, 0.4953, 0.5673, 0.4607],
         [0.5790, 0.7061, 0.3406, 0.7670]]])
3
torch.Size([1, 3, 4])


In [ ]:
  # Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=[224, 224, 3]) # height, width, color channels
print(random_image_size_tensor)
print(random_image_size_tensor.ndim)
print(random_image_size_tensor.shape)

tensor([[[5.0306e-05, 3.8552e-01, 8.2591e-01],
         [6.3393e-01, 7.5027e-01, 9.7563e-01],
         [5.3479e-01, 4.5663e-01, 6.5843e-01],
         ...,
         [3.1221e-01, 2.8334e-01, 5.0840e-01],
         [6.1440e-01, 3.0727e-02, 1.7586e-01],
         [7.4543e-01, 6.0876e-01, 6.8414e-02]],

        [[8.7041e-03, 5.6621e-01, 9.1626e-01],
         [5.9408e-01, 7.3438e-01, 2.7053e-01],
         [3.3373e-01, 8.9148e-01, 7.8515e-02],
         ...,
         [9.2474e-02, 7.2350e-01, 1.8893e-01],
         [7.9915e-01, 4.4235e-01, 6.4453e-01],
         [9.9926e-01, 8.6364e-01, 3.3050e-01]],

        [[3.6391e-01, 6.9047e-01, 5.4529e-01],
         [9.1007e-01, 5.3788e-02, 8.1666e-01],
         [7.4077e-01, 9.1754e-01, 5.3923e-01],
         ...,
         [1.2605e-01, 8.7363e-01, 7.7427e-01],
         [9.5211e-01, 6.5799e-01, 9.5053e-01],
         [2.9530e-01, 4.9832e-01, 4.7358e-01]],

        ...,

        [[5.3705e-01, 7.5431e-01, 5.4161e-01],
         [5.4169e-01, 5.9763e-01, 4.2022e-01]

### Zeros and Ones

In [ ]:
# Create a tesnor of all zeros
zeros = torch.zeros(size=[3,4])
zeros, zeros * random_tensor

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]))

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=[3,4])
ones, ones * random_tensor

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[[0.0503, 0.9106, 0.7554, 0.0068],
          [0.4413, 0.4953, 0.5673, 0.4607],
          [0.5790, 0.7061, 0.3406, 0.7670]]]))

In [ ]:
 ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [ ]:
# use torch.range
torch.arange(10, 120)

tensor([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
         24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
        108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119])

In [ ]:
range = torch.arange(start=10, end=1000, step=5)
range

tensor([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,  75,
         80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145,
        150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200, 205, 210, 215,
        220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285,
        290, 295, 300, 305, 310, 315, 320, 325, 330, 335, 340, 345, 350, 355,
        360, 365, 370, 375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425,
        430, 435, 440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495,
        500, 505, 510, 515, 520, 525, 530, 535, 540, 545, 550, 555, 560, 565,
        570, 575, 580, 585, 590, 595, 600, 605, 610, 615, 620, 625, 630, 635,
        640, 645, 650, 655, 660, 665, 670, 675, 680, 685, 690, 695, 700, 705,
        710, 715, 720, 725, 730, 735, 740, 745, 750, 755, 760, 765, 770, 775,
        780, 785, 790, 795, 800, 805, 810, 815, 820, 825, 830, 835, 840, 845,
        850, 855, 860, 865, 870, 875, 880, 885, 890, 895, 900, 9

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0])