<a href="https://colab.research.google.com/github/deepen-404/pytorch-machine-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch;
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.4.1+cu121


In [8]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [12]:
# Get Scalar as a python int
scalar.item()

7

In [13]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [14]:
vector.ndim

1

In [26]:
# no of pair of sq bracets = no of dimensions

vector.shape

torch.Size([2])

In [29]:
# MATRIX
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])
print(MATRIX.ndim)
print(MATRIX.shape)
MATRIX

2
torch.Size([2, 2])


tensor([[1, 2],
        [3, 4]])

In [30]:
print(MATRIX[0])
print(MATRIX[1])

tensor([1, 2])
tensor([3, 4])


In [40]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


In [41]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 4, 3])


In [43]:
TENSOR = torch.tensor([[[1, 2, 3, 4],
                        [1, 2, 3, 4],
                        [4, 5, 6, 4],
                        [7, 8, 9, 4]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3, 4],
         [1, 2, 3, 4],
         [4, 5, 6, 4],
         [7, 8, 9, 4]]])
3
torch.Size([1, 4, 4])


In [46]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[1, 2, 3],
                        [1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([2, 4, 3])
